@url = https://8080-jeffevargas-apiquiz2024-577fafnpxik.ws-us116.gitpod.io

###
GET {{url}}/categorias

###
POST {{url}}/categorias
Content-Type: application/json

{
    "nome": "Arquitetura de APIs"
}